server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    sql-migration-prefix: v
    table: schema_version
