server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:~/test-task
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    sql-migration-prefix: v
    table: schema_version
